import React from 'react';
import { FileText, Upload, Activity, Cpu, CheckCircle } from 'lucide-react';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';

/**
 * InstructionsPage Component
 * Purpose: Guides the user through the clinical workflow.
 */
const InstructionsPage = ({ onNavigate }) => {
    const steps = [
        {
            step: "01",
            title: "Prepare your Dataset",
            desc: "Ensure your ECG signal is in the `.npy` format. The system is calibrated for single-channel leads sampled at 500 Hz.",
            icon: FileText
        },
        {
            step: "02",
            title: "Upload Clinical Signal",
            desc: "Navigate to the 'Upload ECG' tab and drag-and-drop your file. The system will automatically initiate the neural processing protocol.",
            icon: Upload
        },
        {
            step: "03",
            title: "Interactive Visualization",
            desc: "Once processed, use the interactive chart to zoom into specific wave segments. P-waves, QRS complexes, and T-waves are automatically segmented.",
            icon: Activity
        },
        {
            step: "04",
            title: "Review AI Explanation",
            desc: "Read the clinical rationale generated by the XAI module. It explains the relationship between dissociated P-waves and potential AV blocks.",
            icon: Cpu
        },
        {
            step: "05",
            title: "Export Results",
            desc: "Click 'Export Clinical PDF' to generate a professional research report containing all metrics, visualizations, and diagnostic conclusions.",
            icon: CheckCircle
        }
    ];

    return (
        <div className="flex-1 container mx-auto p-12 max-w-4xl animate-in fade-in slide-in-from-bottom-8 duration-700">
            <header className="text-center mb-16">
                <h2 className="text-3xl font-black text-slate-800 mb-4 tracking-tight">Clinical Workflow Guide</h2>
                <p className="text-slate-500 font-medium">
                    Follow this protocol to analyze ECG signals and generate AI-supported clinical findings.
                </p>
            </header>

            <div className="grid gap-8">
                {steps.map((item) => (
                    <Card key={item.step} variant="interactive" padding="md" className="flex gap-6 items-start">
                        <div className="flex-shrink-0 w-12 h-12 bg-blue-50 rounded-2xl flex items-center justify-center font-black text-blue-600 transition-colors">
                            {item.step}
                        </div>
                        <div className="space-y-1">
                            <h4 className="text-lg font-black text-slate-800 flex items-center gap-2">
                                <item.icon className="w-5 h-5 text-blue-400" />
                                {item.title}
                            </h4>
                            <p className="text-slate-500 text-sm leading-relaxed">{item.desc}</p>
                        </div>
                    </Card>
                ))}
            </div>

            <footer className="mt-16 text-center">
                <Button size="lg" onClick={() => onNavigate('analysis')}>
                    Proceed to Upload
                </Button>
            </footer>
        </div>
    );
};

export default InstructionsPage;
