import React from 'react';
import { FileText, Upload, Activity, Cpu, CheckCircle } from 'lucide-react';

const steps = [
    {
        num: '01',
        icon: FileText,
        title: 'Prepare your Dataset',
        desc: 'Ensure your ECG signal is in the .npy format. The system is calibrated for single-channel leads sampled at 500 Hz.',
    },
    {
        num: '02',
        icon: Upload,
        title: 'Upload Clinical Signal',
        desc: "Navigate to the 'Upload ECG' tab and drag-and-drop your file. The system will automatically initiate the neural processing protocol.",
    },
    {
        num: '03',
        icon: Activity,
        title: 'Interactive Visualization',
        desc: 'Once processed, use the interactive chart to zoom into specific wave segments. P-waves, QRS complexes, and T-waves are automatically segmented.',
    },
    {
        num: '04',
        icon: Cpu,
        title: 'Review AI Explanation',
        desc: 'Read the clinical rationale generated by the XAI module. It explains the relationship between dissociated P-waves and potential AV blocks.',
    },
    {
        num: '05',
        icon: CheckCircle,
        title: 'Export Results',
        desc: "Click 'Generate PDF Report' to export a professional research report containing all metrics, visualizations, and diagnostic conclusions.",
    },
];

const InstructionsPage = ({ onNavigate }) => (
    <div className="page-shell">
        <div className="instr-shell">
            <header className="instr-header">
                <h1 className="instr-title">Clinical Workflow Guide</h1>
                <p className="instr-subtitle">
                    Follow this protocol to analyze ECG signals and generate{' '}
                    <a href="#" onClick={() => onNavigate('analysis')}>AI-supported</a> clinical findings.
                </p>
            </header>

            <div className="instr-steps">
                {steps.map(({ num, icon: Icon, title, desc }) => (
                    <div className="instr-step" key={num}>
                        <div className="instr-step-num">{num}</div>
                        <div className="instr-step-body">
                            <div className="instr-step-title">
                                <Icon style={{ width: 16, height: 16, color: 'var(--brand-mid)', flexShrink: 0 }} />
                                {title}
                            </div>
                            <p className="instr-step-desc">{desc}</p>
                        </div>
                    </div>
                ))}
            </div>

            <footer className="instr-footer">
                <button className="btn-primary" onClick={() => onNavigate('analysis')}>
                    <Upload style={{ width: 16, height: 16 }} />
                    Proceed to Upload
                </button>
            </footer>
        </div>
    </div>
);

export default InstructionsPage;
